name: at_streaming
version: "0.1.0"

profile: at_streaming
config-version: 2

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]

clean-targets:
  - target
  - dbt_packages

seeds:
  at_streaming:
    +schema: gtfs_static
    gtfs_routes:
      +column_types:
        route_id: string
        agency_id: string
        route_short_name: string
        route_long_name: string
        route_desc: string
        route_type: integer
        route_url: string
        route_color: string
        route_text_color: string
        route_sort_order: string
        contract_id: string
    gtfs_stops:
      +column_types:
        stop_id: string
        stop_code: string
        stop_name: string
        stop_desc: string
        stop_lat: double
        stop_lon: double
        zone_id: string
        stop_url: string
        location_type: integer
        parent_station: string
        stop_timezone: string
        platform_code: string
        wheelchair_boarding: integer
        start_date: string
        end_date: string

models:
  at_streaming:
    staging:
      +materialized: view
    core:
      +materialized: table
    marts:
      +materialized: incremental
      +incremental_strategy: append
