name: at_streaming
version: "0.1.0"

profile: at_streaming
config-version: 2

model-paths: ["models"]
seed-paths: ["seeds"]
test-paths: ["tests"]

clean-targets:
  - target
  - dbt_packages

seeds:
  at_streaming:
    gtfs_routes:
      +column_types:
        route_id: varchar
        route_short_name: varchar
        route_long_name: varchar
        route_type: integer
    gtfs_stops:
      +column_types:
        stop_id: varchar
        stop_name: varchar
        stop_lat: double
        stop_lon: double
        stop_code: varchar

models:
  at_streaming:
    staging:
      +materialized: view
    core:
      +materialized: table
    marts:
      +materialized: incremental
      +incremental_strategy: append
